//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 198.146373 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class OPF_Takistani_Militia {
        displayName = "Takistani Militia";
        side = 0;
        flag = "ca\Ca_E\data\flag_tkm_co.paa";
        icon = "ca\Ca_E\data\flag_tkm_co.paa";
        priority = 1;
    };

    class BLU_Takistani_Militia {
        displayName = "Takistani Militia";
        side = 1;
        flag = "ca\Ca_E\data\flag_tka_co.paa";
        icon = "ca\Ca_E\data\flag_tka_co.paa";
        priority = 1;
    };

    class IND_Takistani_Militia {
        displayName = "Takistani Militia";
        side = 2;
        flag = "ca\Ca_E\data\flag_tkg_co.paa";
        icon = "ca\Ca_E\data\flag_tkg_co.paa";
        priority = 1;
    };
};

class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhsgref_ins_btr60;
    class rhsgref_ins_btr60_OCimport_01 : rhsgref_ins_btr60 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_btr60_OCimport_02 : rhsgref_ins_btr60_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class TBan_Recruit2;
    class TBan_Recruit2_OCimport_01 : TBan_Recruit2 { scope = 0; class EventHandlers; };
    class TBan_Recruit2_OCimport_02 : TBan_Recruit2_OCimport_01 { class EventHandlers; };

    class rhsgref_ins_btr70;
    class rhsgref_ins_btr70_OCimport_01 : rhsgref_ins_btr70 { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_ins_btr70_OCimport_02 : rhsgref_ins_btr70_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class Commander_Out;
        };
    };

    class I_Sniper_F;
    class I_Sniper_F_OCimport_01 : I_Sniper_F { scope = 0; class EventHandlers; };
    class I_Sniper_F_OCimport_02 : I_Sniper_F_OCimport_01 { class EventHandlers; };

    class rhsgref_nat_uaz;
    class rhsgref_nat_uaz_OCimport_01 : rhsgref_nat_uaz { scope = 0; class EventHandlers; };
    class rhsgref_nat_uaz_OCimport_02 : rhsgref_nat_uaz_OCimport_01 { scope = 0; class EventHandlers; };

    class rhsgref_nat_uaz_open;
    class rhsgref_nat_uaz_open_OCimport_01 : rhsgref_nat_uaz_open { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_nat_uaz_open_OCimport_02 : rhsgref_nat_uaz_open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class rhsgref_nat_uaz_dshkm;
    class rhsgref_nat_uaz_dshkm_OCimport_01 : rhsgref_nat_uaz_dshkm { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_nat_uaz_dshkm_OCimport_02 : rhsgref_nat_uaz_dshkm_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class rhsgref_tla_offroad;
    class rhsgref_tla_offroad_OCimport_01 : rhsgref_tla_offroad { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_tla_offroad_OCimport_02 : rhsgref_tla_offroad_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class rhsgref_tla_offroad_armed;
    class rhsgref_tla_offroad_armed_OCimport_01 : rhsgref_tla_offroad_armed { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_tla_offroad_armed_OCimport_02 : rhsgref_tla_offroad_armed_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
        };
    };

    class rhsgref_nat_2b14;

    class rhsgref_cdf_gaz66o;
    class rhsgref_cdf_gaz66o_OCimport_01 : rhsgref_cdf_gaz66o { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_gaz66o_OCimport_02 : rhsgref_cdf_gaz66o_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class rhsgref_cdf_ural_open;
    class rhsgref_cdf_ural_open_OCimport_01 : rhsgref_cdf_ural_open { scope = 0; class EventHandlers; class Turrets; };
    class rhsgref_cdf_ural_open_OCimport_02 : rhsgref_cdf_ural_open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class rhsgref_ins_DSHKM_Mini_TriPod;
    class rhsgref_ins_DSHKM;

    class TBan_Recruit6NH;
    class TBan_Recruit6NH_OCimport_01 : TBan_Recruit6NH { scope = 0; class EventHandlers; };
    class TBan_Recruit6NH_OCimport_02 : TBan_Recruit6NH_OCimport_01 { class EventHandlers; };

    class TBan_Recruit5;
    class TBan_Recruit5_OCimport_01 : TBan_Recruit5 { scope = 0; class EventHandlers; };
    class TBan_Recruit5_OCimport_02 : TBan_Recruit5_OCimport_01 { class EventHandlers; };

    class Haji_Matin;
    class Haji_Matin_OCimport_01 : Haji_Matin { scope = 0; class EventHandlers; };
    class Haji_Matin_OCimport_02 : Haji_Matin_OCimport_01 { class EventHandlers; };

    class TBan_Recruit4;
    class TBan_Recruit4_OCimport_01 : TBan_Recruit4 { scope = 0; class EventHandlers; };
    class TBan_Recruit4_OCimport_02 : TBan_Recruit4_OCimport_01 { class EventHandlers; };

    class TBan_Recruit3;
    class TBan_Recruit3_OCimport_01 : TBan_Recruit3 { scope = 0; class EventHandlers; };
    class TBan_Recruit3_OCimport_02 : TBan_Recruit3_OCimport_01 { class EventHandlers; };

    class TBan_Recruit2NH;
    class TBan_Recruit2NH_OCimport_01 : TBan_Recruit2NH { scope = 0; class EventHandlers; };
    class TBan_Recruit2NH_OCimport_02 : TBan_Recruit2NH_OCimport_01 { class EventHandlers; };

    class RHS_ZU23_VDV;
    class RHS_ZU23_VDV_OCimport_01 : RHS_ZU23_VDV { scope = 0; class EventHandlers; class Turrets; };
    class RHS_ZU23_VDV_OCimport_02 : RHS_ZU23_VDV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    ////////////////////////////////////////////////////////////////////////
    //       Men
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_Rifleman_AKM_01 : TBan_Recruit2NH_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_AKM_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AKM)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan02NH";

        linkedItems[] = {"V_BandollierB_oli"};
        respawnlinkedItems[] = {"V_BandollierB_oli"};

        weapons[] = {"rhs_weap_akm"};
        respawnWeapons[] = {"rhs_weap_akm"};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};

		ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_02Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_05Hat","",{},{"","","","","",""}},
		};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_AKM_01 : O_TakistaniMilitia_Rifleman_AKM_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_AKM_01 : O_TakistaniMilitia_Rifleman_AKM_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };
    

    class O_TakistaniMilitia_Rifleman_AKMS_01 : TBan_Recruit4_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_AKMS_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AKMS)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan06NH";

        linkedItems[] = {"V_TacChestrig_grn_F"};
        respawnlinkedItems[] = {"V_TacChestrig_grn_F"};

        weapons[] = {"rhs_weap_akms"};
        respawnWeapons[] = {"rhs_weap_akms"};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};

		ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_02Hat","",{},{"","","","","",""}},
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
		};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_AKMS_01 : O_TakistaniMilitia_Rifleman_AKMS_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_AKMS_01 : O_TakistaniMilitia_Rifleman_AKMS_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_Rifleman_M1_01 : TBan_Recruit2_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_M1_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (M1)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan02NH";

        linkedItems[] = {"V_BandollierB_oli"};
        respawnlinkedItems[] = {"V_BandollierB_oli"};

        weapons[] = {"rhs_weap_m1garand_sa43"};
        respawnWeapons[] = {"rhs_weap_m1garand_sa43"};

        magazines[] = {"rhsgref_8Rnd_762x63_M2B_M1rifle","rhsgref_8Rnd_762x63_M2B_M1rifle"};
        respawnMagazines[] = {"rhsgref_8Rnd_762x63_M2B_M1rifle","rhsgref_8Rnd_762x63_M2B_M1rifle"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"Afghan_05Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m1garand_sa43","","","",{"rhsgref_8Rnd_762x63_M2B_M1rifle",8},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_8Rnd_762x63_M2B_M1rifle",8,8}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
		};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_M1_01 : O_TakistaniMilitia_Rifleman_M1_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_M1_01 : O_TakistaniMilitia_Rifleman_M1_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_Rifleman_M70_01 : TBan_Recruit2_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_AKM_01.jpg";
        author = "Landric / TikaKino";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (M70)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan04";

        linkedItems[] = {"V_BandollierB_oli"};
        respawnlinkedItems[] = {"V_BandollierB_oli"};

        weapons[] = {"rhs_weap_m70b3n"};
        respawnWeapons[] = {"rhs_weap_m70b3n"};

        magazines[] = {"rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67"};
        respawnMagazines[] = {"rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67","rhssaf_30Rnd_762x39mm_M67"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m70b3n","","","",{"rhssaf_30Rnd_762x39mm_M67",30},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhssaf_30Rnd_762x39mm_M67",5,30}}},{},"Afghan_02Hat","",{},{"","","","","",""}},
		};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_M70_01 : O_TakistaniMilitia_Rifleman_M70_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_M70_01 : O_TakistaniMilitia_Rifleman_M70_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    class O_TakistaniMilitia_Rifleman_SAVZ58_01 : TBan_Recruit2_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_AKM_01.jpg";
        author = "Landric / TikaKino";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Sa vz. 58)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan05";

        linkedItems[] = {"V_BandollierB_oli"};
        respawnlinkedItems[] = {"V_BandollierB_oli"};

        weapons[] = {"rhs_weap_savz58v"};
        respawnWeapons[] = {"rhs_weap_savz58v"};

        magazines[] = {"rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58","rhs_30Rnd_762x39mm_Savz58"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"Afghan_06Hat","",{},{"","","","","",""}},
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"Afghan_05Hat","",{},{"","","","","",""}},
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_savz58v","","","",{"rhs_30Rnd_762x39mm_Savz58",30},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhs_30Rnd_762x39mm_Savz58",5,30}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
		};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_SAVZ58_01 : O_TakistaniMilitia_Rifleman_SAVZ58_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_SAVZ58_01 : O_TakistaniMilitia_Rifleman_SAVZ58_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    class O_TakistaniMilitia_Rifleman_Mosin_01 : TBan_Recruit3_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_Mosin_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Mosin)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan03";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_m38"};
        respawnWeapons[] = {"rhs_weap_m38"};

        magazines[] = {"rhsgref_5Rnd_762x54_m38","rhsgref_5Rnd_762x54_m38"};
        respawnMagazines[] = {"rhsgref_5Rnd_762x54_m38","rhsgref_5Rnd_762x54_m38"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"Afghan_05Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m38","","","",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_5Rnd_762x54_m38",8,5}}},{},"Afghan_06Hat","",{},{"","","","","",""}},
		};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_Mosin_01 : O_TakistaniMilitia_Rifleman_Mosin_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_Mosin_01 : O_TakistaniMilitia_Rifleman_Mosin_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };
   
	class O_TakistaniMilitia_SMG_M3_01 : TBan_Recruit3_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Medic_01.jpg";
        author = "TikaKino";
        scope = 2;
        scopeCurator = 2;
        displayName = "SMG (M3)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan03";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};

        magazines[] = {"rhsgref_30Rnd_1143x23_M1911B_SMG","rhsgref_30Rnd_1143x23_M1911B_SMG"};
        respawnMagazines[] = {"rhsgref_30Rnd_1143x23_M1911B_SMG","rhsgref_30Rnd_1143x23_M1911B_SMG"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"Afghan_02Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_m3a1","","","",{"rhsgref_30Rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_30Rnd_1143x23_M1911B_SMG",5,30}}},{},"Afghan_05Hat","",{},{"","","","","",""}},
		};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_SMG_M3_01 : O_TakistaniMilitia_SMG_M3_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_SMG_M3_01 : O_TakistaniMilitia_SMG_M3_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

	class O_TakistaniMilitia_SMG_M84_01 : TBan_Recruit3_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Medic_01.jpg";
        author = "TikaKino";
        scope = 2;
        scopeCurator = 2;
        displayName = "SMG (M84A)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan01NH";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_scorpion"};
        respawnWeapons[] = {"rhs_weap_scorpion"};

        magazines[] = {"rhsgref_20rnd_765x17_vz61","rhsgref_20rnd_765x17_vz61"};
        respawnMagazines[] = {"rhsgref_20rnd_765x17_vz61","rhsgref_20rnd_765x17_vz61"};

        ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"Afghan_02Hat","",{},{"","","","","",""}},
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"Afghan_03Hat","",{},{"","","","","",""}},
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chestrig",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"Afghan_06Hat","",{},{"","","","","",""}},
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",4}}},{"V_Bandollier_oli",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",4}}},{"V_Bandollier_rgr",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"","",{},{"","","","","",""}},
			{{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",4}}},{"rhsgref_chicom",{{"rhsgref_20rnd_765x17_vz61",6,20}}},{},"Afghan_01Hat","",{},{"","","","","",""}},
		};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_SMG_M84_01 : O_TakistaniMilitia_SMG_M84_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_SMG_M84_01 : O_TakistaniMilitia_SMG_M84_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    class O_TakistaniMilitia_Medic_01 : Haji_Matin_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Medic_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        
        attendant=1;
        icon="iconManMedic";

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan03";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_m3a1"};
        respawnWeapons[] = {"rhs_weap_m3a1"};

        magazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};
        respawnMagazines[] = {"rhsgref_30rnd_1143x23_M1911B_SMG","rhsgref_30rnd_1143x23_M1911B_SMG"};

        backpack = "rhs_medic_bag";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m3a1","","","",{"rhsgref_30rnd_1143x23_M1911B_SMG",30},{},""},{},{},{"U_Afghan03",{{"rhsgref_30rnd_1143x23_M1911B_SMG",1,30}}},{},{"rhs_medic_bag",{{"ACE_bloodIV_500",2},{"ACE_fieldDressing",24},{"ACE_tourniquet",4},{"ACE_splint",2},{"rhsgref_30rnd_1143x23_M1911B_SMG",3,30}}},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Medic_01 : O_TakistaniMilitia_Medic_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Medic_01 : O_TakistaniMilitia_Medic_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_Machinegunner_PKM_01 : TBan_Recruit2_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Machinegunner_PKM_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machinegunner (PKM)";
        
        icon = "iconManMG";
        textSingular = "$STR_A3_nameSound_veh_infantry_MG_s";
        textPlural = "$STR_A3_nameSound_veh_infantry_MG_p";
        nameSound = "veh_infantry_MG_s";
        
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan02";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_pkm"};
        respawnWeapons[] = {"rhs_weap_pkm"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};

        backpack = "rhs_sidor";

		ALiVE_orbatCreator_loadout[] = {
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan01NH",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"Afghan_05Hat","",{},{"","","","","",""}},
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan02NH",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"Afghan_04Hat","",{},{"","","","","",""}},
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"Afghan_05Hat","",{},{"","","","","",""}},
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan04",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"","",{},{"","","","","",""}},
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan05",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"","",{},{"","","","","",""}},
			{{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"U_Afghan06NH",{{"ACE_fieldDressing",2}}},{},{"rhs_sidor",{{"rhs_100Rnd_762x54mmR_green",2,100}}},"Afghan_02Hat","",{},{"","","","","",""}},
		};

        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _loadout = selectRandom _loadout; _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Machinegunner_PKM_01 : O_TakistaniMilitia_Machinegunner_PKM_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Machinegunner_PKM_01 : O_TakistaniMilitia_Machinegunner_PKM_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_AT_Specialist_RPG_01 : TBan_Recruit6NH_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_AT_Specialist_RPG_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Specialist (RPG)";

        icon = "iconManAT";
        textSingular = "$STR_A3_nameSound_veh_infantry_AT_s";
        textPlural = "$STR_A3_nameSound_veh_infantry_AT_p";
        nameSound = "veh_infantry_AT_s";

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan06";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_m14","rhs_weap_rpg7"};
        respawnWeapons[] = {"rhs_weap_m14","rhs_weap_rpg7"};

        magazines[] = {"rhsusf_20Rnd_762x51_m80_Mag","rhs_rpg7_PG7V_mag","rhsusf_20Rnd_762x51_m80_Mag"};
        respawnMagazines[] = {"rhsusf_20Rnd_762x51_m80_Mag","rhs_rpg7_PG7V_mag","rhsusf_20Rnd_762x51_m80_Mag"};

        backpack = "rhs_rpg_empty";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m14","","","",{"rhsusf_20Rnd_762x51_m80_Mag",20},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7V_mag",1},{},""},{},{"U_Afghan06",{{"ACE_fieldDressing",3},{"rhsusf_20Rnd_762x51_m80_Mag",1,20}}},{},{"rhs_rpg_empty",{{"rhsusf_20Rnd_762x51_m80_Mag",4,20},{"rhs_rpg7_PG7V_mag",1,1},{"rhs_rpg7_PG7VL_mag",1,1}}},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_AT_Specialist_RPG_01 : O_TakistaniMilitia_AT_Specialist_RPG_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_AT_Specialist_RPG_01 : O_TakistaniMilitia_AT_Specialist_RPG_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_AA_Specialist_Stinger_01 : TBan_Recruit5_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_AA_Specialist_Stinger_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Specialist (Stinger)";
        icon = "iconManAT";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan05";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_aks74u","rhs_weap_fim92"};
        respawnWeapons[] = {"rhs_weap_aks74u","rhs_weap_fim92"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_fim92_mag","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_fim92_mag","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "B_Carryall_cbr";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74un","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{"rhs_weap_fim92","","","",{"rhs_fim92_mag",1},{},""},{},{"U_Afghan05",{{"ACE_fieldDressing",3},{"rhs_30Rnd_545x39_7N6M_AK",1,30}}},{},{"B_Carryall_cbr",{{"rhs_fim92_mag",1,1},{"rhs_30Rnd_545x39_7N6M_AK",4,30}}},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_AA_Specialist_Stinger_01 : O_TakistaniMilitia_AA_Specialist_Stinger_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_AA_Specialist_Stinger_01 : O_TakistaniMilitia_AA_Specialist_Stinger_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_AA_Specialist_Igla_01 : TBan_Recruit5_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_AA_Specialist_Igla_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Specialist (Igla)";
        icon = "iconManAT";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan05";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_aks74u","rhs_weap_igla"};
        respawnWeapons[] = {"rhs_weap_aks74u","rhs_weap_igla"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9k38_rocket","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_mag_9k38_rocket","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "B_Carryall_cbr";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{"rhs_weap_igla","","","",{"rhs_mag_9k38_rocket",1},{},""},{},{"U_Afghan05",{{"ACE_fieldDressing",2},{"rhs_30Rnd_545x39_7N6M_AK",2,30}}},{},{"B_Carryall_cbr",{{"rhs_mag_9k38_rocket",1,1},{"rhs_30Rnd_545x39_7N6M_AK",4,30}}},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_AA_Specialist_Igla_01 : O_TakistaniMilitia_AA_Specialist_Igla_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_AA_Specialist_Igla_01 : O_TakistaniMilitia_AA_Specialist_Igla_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_Sharpshooter_Mosin_01 : TBan_Recruit3_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Sharpshooter_Mosin_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sharpshooter (Mosin)";

        textSingular = "$STR_A3_nameSound_veh_infantry_sniper_s";
        textPlural = "$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound = "veh_infantry_sniper_s"; 

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan03NH";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_m38_rail"};
        respawnWeapons[] = {"rhs_weap_m38_rail"};

        magazines[] = {"rhsgref_5Rnd_762x54_m38","rhsgref_5Rnd_762x54_m38"};
        respawnMagazines[] = {"rhsgref_5Rnd_762x54_m38","rhsgref_5Rnd_762x54_m38"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m38_rail","","","optic_KHS_old",{"rhsgref_5Rnd_762x54_m38",5},{},""},{},{},{"U_Afghan03NH",{{"ACE_fieldDressing",4},{"ACE_10Rnd_762x51_M118LR_Mag",3,10}}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Sharpshooter_Mosin_01 : O_TakistaniMilitia_Sharpshooter_Mosin_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Sharpshooter_Mosin_01 : O_TakistaniMilitia_Sharpshooter_Mosin_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_Sniper_Dragunov_01 : Haji_Matin_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Sniper_Dragunov_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper (Dragunov)";

        textSingular = "$STR_A3_nameSound_veh_infantry_sniper_s";
        textPlural = "$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound = "veh_infantry_sniper_s"; 

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan04";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_svdp"};
        respawnWeapons[] = {"rhs_weap_svdp"};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svdp","","","rhs_acc_pso1m21",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{},{"U_Afghan04",{{"FirstAidKit",1},{"ACE_fieldDressing",4},{"rhs_10Rnd_762x54mmR_7N1",4,10}}},{},{},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Sniper_Dragunov_01 : O_TakistaniMilitia_Sniper_Dragunov_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Sniper_Dragunov_01 : O_TakistaniMilitia_Sniper_Dragunov_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };


    class O_TakistaniMilitia_IED_Specialist_M84A_01 : TBan_Recruit6NH_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_IED_Specialist_M84A_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "IED Specialist (M84A)";

        canDeactivateMines=1;
        Engineer=1;
        icon = "iconManEngineer";

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan01NH";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {"rhs_weap_scorpion","Binocular", Put};
        respawnWeapons[] = {"rhs_weap_scorpion","Binocular", Put};

        magazines[] = {"rhsgref_20rnd_765x17_vz61","rhsgref_20rnd_765x17_vz61"};
        respawnMagazines[] = {"rhsgref_20rnd_765x17_vz61","rhsgref_20rnd_765x17_vz61"};

        backpack = "B_Messenger_Coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_scorpion","","","",{"rhsgref_20rnd_765x17_vz61",20},{},""},{},{},{"U_Afghan01NH",{{"FirstAidKit",1},{"ACE_fieldDressing",4},{"rhsgref_20rnd_765x17_vz61",3,20}}},{},{"B_Messenger_Coyote_F",{{"ACE_Cellphone",1},{"ACE_DeadManSwitch",1},{"IEDLandSmall_Remote_Mag",1,1},{"IEDUrbanSmall_Remote_Mag",2,1},{"rhs_mine_Mk2_tripwire_mag",1,1}}},"","",{"Binocular","","","",{},{},""},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_IED_Specialist_M84A_01 : O_TakistaniMilitia_IED_Specialist_M84A_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_IED_Specialist_M84A_01 : O_TakistaniMilitia_IED_Specialist_M84A_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    class O_TakistaniMilitia_IED_Specialist_Unarmed_01 : TBan_Recruit6NH_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_IED_Specialist_Unarmed_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "IED Specialist (Unarmed)";

        canDeactivateMines=1;
        Engineer=1;
        icon = "iconManEngineer";

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "U_Afghan01NH";

        linkedItems[] = {};
        respawnlinkedItems[] = {};

        weapons[] = {Put, Throw};
        respawnWeapons[] = {Put, Throw};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_Messenger_Coyote_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_Afghan01NH",{{"FirstAidKit",1},{"ACE_fieldDressing",4},{"ACE_Cellphone",2},{"ACE_DeadManSwitch",1}}},{},{"B_Messenger_Coyote_F",{{"IEDUrbanSmall_Remote_Mag",2,1},{"IEDLandSmall_Remote_Mag",1,1},{"rhs_mine_Mk2_tripwire_mag",1,1}}},"","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_IED_Specialist_Unarmed_01 : O_TakistaniMilitia_IED_Specialist_Unarmed_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_IED_Specialist_Unarmed_01 : O_TakistaniMilitia_IED_Specialist_Unarmed_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    ////////////////////////////////////////////////////////////////////////
    //       Men (Special Forces)
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_Rifleman_SF_AKM_01 : I_Sniper_F_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Rifleman_SF_AKM_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AKM)";
        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "rhsgref_uniform_woodland_olive";

        linkedItems[] = {"V_BandollierB_blk","Afghan_02Hat","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","Afghan_02Hat","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_akm","Binocular", Throw};
        respawnWeapons[] = {"rhs_weap_akm","Binocular", Throw};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"rhsgref_uniform_woodland_olive",{{"rhs_30Rnd_762x39mm_bakelite",2,30},{"MiniGrenade",2,1}}},{"V_BandollierB_blk",{{"ACE_fieldDressing",6},{"rhs_30Rnd_762x39mm_bakelite",4,30}}},{},"Afghan_02Hat","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Rifleman_SF_AKM_01 : O_TakistaniMilitia_Rifleman_SF_AKM_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Rifleman_SF_AKM_01 : O_TakistaniMilitia_Rifleman_SF_AKM_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };
    

    class O_TakistaniMilitia_Sniper_SF_Dragunov_01 : O_TakistaniMilitia_Rifleman_SF_AKM_01 {
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper (Dragunov)";

        textSingular = "$STR_A3_nameSound_veh_infantry_sniper_s";
        textPlural = "$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound = "veh_infantry_sniper_s"; 

        side = 0;
        faction = "OPF_Takistani_Militia";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default","NoGlasses"};

        uniformClass = "rhsgref_uniform_flecktarn";

        linkedItems[] = {"V_BandollierB_blk","Afghan_04Hat","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","Afghan_04Hat","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_svdp","Binocular", Throw};
        respawnWeapons[] = {"rhs_weap_svdp","Binocular", Throw};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhs_10Rnd_762x54mmR_7N1"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svdp","","","rhs_acc_pso1m21",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{},{"rhsgref_uniform_flecktarn",{{"MiniGrenade",2,1},{"rhs_10Rnd_762x54mmR_7N1",3,10}}},{"V_BandollierB_blk",{{"ACE_fieldDressing",6},{"rhs_10Rnd_762x54mmR_7N14",6,10},{"MiniGrenade",2,1}}},{},"Afghan_04Hat","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_Sniper_SF_Dragunov_01 : O_TakistaniMilitia_Sniper_SF_Dragunov_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
    };

    class I_TakistaniMilitia_Sniper_SF_Dragunov_01 : O_TakistaniMilitia_Sniper_SF_Dragunov_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
    };

    ////////////////////////////////////////////////////////////////////////
    //       Artillery
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_2B14_1Podnos_01 : rhsgref_nat_2b14 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_2B14_1Podnos_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "2B14-1 'Podnos'";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_M1_01";
    };

    class B_TakistaniMilitia_2B14_1Podnos_01 : O_TakistaniMilitia_2B14_1Podnos_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_M1_01";

        /*class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_TakistaniMilitia_Rifleman_M1_01"; };
        };*/
    };

    class I_TakistaniMilitia_2B14_1Podnos_01 : O_TakistaniMilitia_2B14_1Podnos_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_M1_01";

        /*class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_TakistaniMilitia_Rifleman_M1_01"; };
        };*/
    };


    ////////////////////////////////////////////////////////////////////////
    //       Turrets
    ////////////////////////////////////////////////////////////////////////


    class O_TakistaniMilitia_ZU_23_2_01 : RHS_ZU23_VDV_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_ZU_23_2_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "ZU-23-2";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_TakistaniMilitia_Rifleman_AKMS_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_ZU_23_2_01 : O_TakistaniMilitia_ZU_23_2_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "B_TakistaniMilitia_Rifleman_AKMS_01"; };
        };
    };

    class I_TakistaniMilitia_ZU_23_2_01 : O_TakistaniMilitia_ZU_23_2_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_TakistaniMilitia_Rifleman_AKMS_01"; };
        };
    };


    class O_TakistaniMilitia_DSHkM_Mini_01 : rhsgref_ins_DSHKM_Mini_TriPod {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_DSHkM_Mini_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "DSHkM (Mini)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_Mosin_01";
    };

    class B_TakistaniMilitia_DSHkM_Mini_01 : O_TakistaniMilitia_DSHkM_Mini_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_Mosin_01";
    };

    class I_TakistaniMilitia_DSHkM_Mini_01 : O_TakistaniMilitia_DSHkM_Mini_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_Mosin_01";
    };


    class O_TakistaniMilitia_DShKM_01 : rhsgref_ins_DSHKM {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_DShKM_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "DShKM";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_M1_01";
    };

    class B_TakistaniMilitia_DShKM_01 : O_TakistaniMilitia_DShKM_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_M1_01";
    };

    class I_TakistaniMilitia_DShKM_01 : O_TakistaniMilitia_DShKM_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_M1_01";
    };

    ////////////////////////////////////////////////////////////////////////
    //       Cars
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_UAZ_3151_01 : rhsgref_nat_uaz_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_UAZ_3151_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKMS_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_ind_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class B_TakistaniMilitia_UAZ_3151_01 : O_TakistaniMilitia_UAZ_3151_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKMS_01";
    };

    class I_TakistaniMilitia_UAZ_3151_01 : O_TakistaniMilitia_UAZ_3151_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKMS_01";
    };


    class O_TakistaniMilitia_UAZ_3151_Open_01 : rhsgref_nat_uaz_open_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_UAZ_3151_Open_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (Open)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKM_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_UAZ_3151_Open_01 : O_TakistaniMilitia_UAZ_3151_Open_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKM_01";
    };

    class I_TakistaniMilitia_UAZ_3151_Open_01 : O_TakistaniMilitia_UAZ_3151_Open_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKM_01";
    };

    class O_TakistaniMilitia_UAZ_3151_DShKM_01 : rhsgref_nat_uaz_dshkm_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_UAZ_3151_DShKM_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (DShKM)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_TakistaniMilitia_UAZ_3151_DShKM_01 : O_TakistaniMilitia_UAZ_3151_DShKM_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };
    };

    class I_TakistaniMilitia_UAZ_3151_DShKM_01 : O_TakistaniMilitia_UAZ_3151_DShKM_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKM_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_TakistaniMilitia_Rifleman_Mosin_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };
    };

    class O_TakistaniMilitia_Offroad_01 : rhsgref_tla_offroad_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Offroad_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKMS_01";
		editorSubcategory = "rhs_EdSubcat_car";
		category = "Car";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_12_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_12_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Guerilla_12";

    };

    class B_TakistaniMilitia_Offroad_01 : O_TakistaniMilitia_Offroad_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKMS_01";
    };

    class I_TakistaniMilitia_Offroad_01 : O_TakistaniMilitia_Offroad_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKMS_01";
    };

    class O_TakistaniMilitia_Offroad_HMG_01 : rhsgref_tla_offroad_armed_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Offroad_HMG_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad (HMG)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKMS_01";
		editorSubcategory = "rhs_EdSubcat_car";
		category = "Car";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "O_TakistaniMilitia_Rifleman_M1_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_12_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_12_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Guerilla_12";

    };

    class B_TakistaniMilitia_Offroad_HMG_01 : O_TakistaniMilitia_Offroad_HMG_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "B_TakistaniMilitia_Rifleman_M1_01"; };
        };
    };

    class I_TakistaniMilitia_Offroad_HMG_01 : O_TakistaniMilitia_Offroad_HMG_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "I_TakistaniMilitia_Rifleman_M1_01"; };
        };
    };


    ////////////////////////////////////////////////////////////////////////
    //       Trucks
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_Truck_Gaz_01 : rhsgref_cdf_gaz66o_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Truck_Gaz_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck (Gaz)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_gaz66_camo\data\gaz66_sand_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_gaz66\data\tent_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\rhs_gaz66_camo\data\rhs_gaz66_kung_sand_co.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\rhs_gaz66_camo\data\rhs_gaz66_ap2kung_sand_co.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\rhs_gaz66_camo\data\rhs_gaz66_repkung_sand_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "rhs_sand";

    };

    class B_TakistaniMilitia_Truck_Gaz_01 : O_TakistaniMilitia_Truck_Gaz_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };
    };

    class I_TakistaniMilitia_Truck_Gaz_01 : O_TakistaniMilitia_Truck_Gaz_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };
    };


    class O_TakistaniMilitia_Truck_Ural_01 : rhsgref_cdf_ural_open_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_Truck_Ural_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck (Ural)";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_khk_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_open_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class B_TakistaniMilitia_Truck_Ural_01 : O_TakistaniMilitia_Truck_Ural_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };
    };

    class I_TakistaniMilitia_Truck_Ural_01 : O_TakistaniMilitia_Truck_Ural_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_AKMS_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };
    };


    ////////////////////////////////////////////////////////////////////////
    //       APCs
    ////////////////////////////////////////////////////////////////////////

    class O_TakistaniMilitia_BTR60_01 : rhsgref_ins_btr60_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_BTR60_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR60";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "O_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_armor\data\btr60_body_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_armor\data\btr60_details_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class B_TakistaniMilitia_BTR60_01 : O_TakistaniMilitia_BTR60_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "B_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };
    };

    class I_TakistaniMilitia_BTR60_01 : O_TakistaniMilitia_BTR60_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "I_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };
    };

    class O_TakistaniMilitia_BTR70_01 : rhsgref_ins_btr70_OCimport_02 {
        editorPreview = "\bf2_takistani_militia\data\preview\TakistaniMilitia_BTR70_01.jpg";
        author = "Landric";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR70";
        side = 0;
        faction = "OPF_Takistani_Militia";
        crew = "O_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "O_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_btr70_camo\data\btr70_1_sand_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_btr70_camo\data\btr70_2_sand_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "rhs_sand";

    };

    class B_TakistaniMilitia_BTR70_01 : O_TakistaniMilitia_BTR70_01 {
        side = 1;
        faction = "BLU_Takistani_Militia";
        crew = "B_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "B_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };
    };

    class I_TakistaniMilitia_BTR70_01 : O_TakistaniMilitia_BTR70_01 {
        side = 2;
        faction = "IND_Takistani_Militia";
        crew = "I_TakistaniMilitia_Rifleman_Mosin_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_TakistaniMilitia_Rifleman_AKMS_01"; };
            class CommanderOptics : CommanderOptics { gunnerType = "I_TakistaniMilitia_Rifleman_AKM_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class Commander_Out : Commander_Out { gunnerType = ""; };
        };
    };

};