//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 198.146373 on Stable branch
// Generated with ALiVE version 1.12.1.2002131
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class OPF_Takistani_Militia {
            name = "Takistani Militia";

            class Infantry {
                name = "Infantry";

                class opf_takistanimilitia_infantry_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_Mosin_01";
                    };
                };

                class opf_takistanimilitia_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Medic_01";
                    };
                };

                class opf_takistanimilitia_infantry_section {
                    name = "Section";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class opf_takistanimilitia_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Sharpshooter_Mosin_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Sniper_Dragunov_01";
                    };
                };

                class opf_takistanimilitia_infantry_aa_team {
                    name = "AA Team";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

                class opf_takistanimilitia_infantry_at_team {
                    name = "AT Team";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class opf_takistanimilitia_motorized_motorized_section {
                    name = "Motorized Section";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Truck_Ural_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class opf_takistanimilitia_motorized_motorized_at_team {
                    name = "Motorized AT Team";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class opf_takistanimilitia_motorized_motorized_aa_team {
                    name = "Motorized AA Team";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class opf_takistanimilitia_mechanized_mechanized_section {
                    name = "Mechanized Section";
                    side = 0;
                    faction = "OPF_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_BTR70_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };



    class WEST {

        class BLU_Takistani_Militia {
            name = "Takistani Militia";

            class Infantry {
                name = "Infantry";

                class blu_takistanimilitia_infantry_patrol {
                    name = "Patrol";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_Mosin_01";
                    };
                };

                class blu_takistanimilitia_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Medic_01";
                    };
                };

                class blu_takistanimilitia_infantry_section {
                    name = "Section";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class blu_takistanimilitia_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Sharpshooter_Mosin_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Sniper_Dragunov_01";
                    };
                };

                class blu_takistanimilitia_infantry_aa_team {
                    name = "AA Team";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

                class blu_takistanimilitia_infantry_at_team {
                    name = "AT Team";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class blu_takistanimilitia_motorized_motorized_section {
                    name = "Motorized Section";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Truck_Ural_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class blu_takistanimilitia_motorized_motorized_at_team {
                    name = "Motorized AT Team";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class blu_takistanimilitia_motorized_motorized_aa_team {
                    name = "Motorized AA Team";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class blu_takistanimilitia_mechanized_mechanized_section {
                    name = "Mechanized Section";
                    side = 1;
                    faction = "BLU_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_BTR70_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };

    class INDEP {

        class IND_Takistani_Militia {
            name = "Takistani Militia";

            class Infantry {
                name = "Infantry";

                class ind_takistanimilitia_infantry_patrol {
                    name = "Patrol";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_Mosin_01";
                    };
                };

                class ind_takistanimilitia_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Medic_01";
                    };
                };

                class ind_takistanimilitia_infantry_section {
                    name = "Section";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class ind_takistanimilitia_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Sharpshooter_Mosin_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Sniper_Dragunov_01";
                    };
                };

                class ind_takistanimilitia_infantry_aa_team {
                    name = "AA Team";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

                class ind_takistanimilitia_infantry_at_team {
                    name = "AT Team";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class ind_takistanimilitia_motorized_motorized_section {
                    name = "Motorized Section";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Truck_Ural_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class ind_takistanimilitia_motorized_motorized_at_team {
                    name = "Motorized AT Team";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

                class ind_takistanimilitia_motorized_motorized_aa_team {
                    name = "Motorized AA Team";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Truck_Gaz_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AA_Specialist_Stinger_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AA_Specialist_Igla_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class ind_takistanimilitia_mechanized_mechanized_section {
                    name = "Mechanized Section";
                    side = 1;
                    faction = "IND_Takistani_Militia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_BTR70_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_AKMS_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Rifleman_M1_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_Machinegunner_PKM_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "I_TakistaniMilitia_AT_Specialist_RPG_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };

};