class CfgPatches {
    class Takistani_Militia {
        units[] = {
            "O_TakistaniMilitia_Rifleman_AKM_01",
            "O_TakistaniMilitia_Rifleman_AKMS_01",
            "O_TakistaniMilitia_Rifleman_M1_01",
            "O_TakistaniMilitia_Rifleman_Mosin_01",
            "O_TakistaniMilitia_Medic_01",
            "O_TakistaniMilitia_Machinegunner_PKM_01",
            "O_TakistaniMilitia_AT_Specialist_RPG_01",
            "O_TakistaniMilitia_AA_Specialist_Stinger_01",
            "O_TakistaniMilitia_AA_Specialist_Igla_01",
            "O_TakistaniMilitia_Sharpshooter_Mosin_01",
            "O_TakistaniMilitia_Sniper_Dragunov_01",
            "O_TakistaniMilitia_IED_Specialist_M84A_01",
            "O_TakistaniMilitia_IED_Specialist_Unarmed_01",
            "O_TakistaniMilitia_Rifleman_SF_AKM_01",
            "O_TakistaniMilitia_Sniper_SF_Dragunov_01",
            "O_TakistaniMilitia_2B14_1Podnos_01",
            "O_TakistaniMilitia_ZU_23_2_01",
            "O_TakistaniMilitia_DSHkM_Mini_01",
            "O_TakistaniMilitia_DShKM_01",
            "O_TakistaniMilitia_UAZ_3151_01",
            "O_TakistaniMilitia_UAZ_3151_Open_01",
            "O_TakistaniMilitia_UAZ_3151_DShKM_01",
            "O_TakistaniMilitia_Offroad_01",
            "O_TakistaniMilitia_Offroad_HMG_01",
            "O_TakistaniMilitia_Truck_Gaz_01",
            "O_TakistaniMilitia_Truck_Ural_01",
            "O_TakistaniMilitia_BTR60_01",
            "O_TakistaniMilitia_BTR70_01",

            "B_TakistaniMilitia_Rifleman_AKM_01",
            "B_TakistaniMilitia_Rifleman_AKMS_01",
            "B_TakistaniMilitia_Rifleman_M1_01",
            "B_TakistaniMilitia_Rifleman_Mosin_01",
            "B_TakistaniMilitia_Medic_01",
            "B_TakistaniMilitia_Machinegunner_PKM_01",
            "B_TakistaniMilitia_AT_Specialist_RPG_01",
            "B_TakistaniMilitia_AA_Specialist_Stinger_01",
            "B_TakistaniMilitia_AA_Specialist_Igla_01",
            "B_TakistaniMilitia_Sharpshooter_Mosin_01",
            "B_TakistaniMilitia_Sniper_Dragunov_01",
            "B_TakistaniMilitia_IED_Specialist_M84A_01",
            "B_TakistaniMilitia_IED_Specialist_Unarmed_01",
            "B_TakistaniMilitia_Rifleman_SF_AKM_01",
            "B_TakistaniMilitia_Sniper_SF_Dragunov_01",
            "B_TakistaniMilitia_2B14_1Podnos_01",
            "B_TakistaniMilitia_ZU_23_2_01",
            "B_TakistaniMilitia_DSHkM_Mini_01",
            "B_TakistaniMilitia_DShKM_01",
            "B_TakistaniMilitia_UAZ_3151_01",
            "B_TakistaniMilitia_UAZ_3151_Open_01",
            "B_TakistaniMilitia_UAZ_3151_DShKM_01",
            "B_TakistaniMilitia_Offroad_01",
            "B_TakistaniMilitia_Offroad_HMG_01",
            "B_TakistaniMilitia_Truck_Gaz_01",
            "B_TakistaniMilitia_Truck_Ural_01",
            "B_TakistaniMilitia_BTR60_01",
            "B_TakistaniMilitia_BTR70_01",

            "I_TakistaniMilitia_Rifleman_AKM_01",
            "I_TakistaniMilitia_Rifleman_AKMS_01",
            "I_TakistaniMilitia_Rifleman_M1_01",
            "I_TakistaniMilitia_Rifleman_Mosin_01",
            "I_TakistaniMilitia_Medic_01",
            "I_TakistaniMilitia_Machinegunner_PKM_01",
            "I_TakistaniMilitia_AT_Specialist_RPG_01",
            "I_TakistaniMilitia_AA_Specialist_Stinger_01",
            "I_TakistaniMilitia_AA_Specialist_Igla_01",
            "I_TakistaniMilitia_Sharpshooter_Mosin_01",
            "I_TakistaniMilitia_Sniper_Dragunov_01",
            "I_TakistaniMilitia_IED_Specialist_M84A_01",
            "I_TakistaniMilitia_IED_Specialist_Unarmed_01",
            "I_TakistaniMilitia_Rifleman_SF_AKM_01",
            "I_TakistaniMilitia_Sniper_SF_Dragunov_01",
            "I_TakistaniMilitia_2B14_1Podnos_01",
            "I_TakistaniMilitia_ZU_23_2_01",
            "I_TakistaniMilitia_DSHkM_Mini_01",
            "I_TakistaniMilitia_DShKM_01",
            "I_TakistaniMilitia_UAZ_3151_01",
            "I_TakistaniMilitia_UAZ_3151_Open_01",
            "I_TakistaniMilitia_UAZ_3151_DShKM_01",
            "I_TakistaniMilitia_Offroad_01",
            "I_TakistaniMilitia_Offroad_HMG_01",
            "I_TakistaniMilitia_Truck_Gaz_01",
            "I_TakistaniMilitia_Truck_Ural_01",
            "I_TakistaniMilitia_BTR60_01",
            "I_TakistaniMilitia_BTR70_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "Taliban_Fighters",
            "rhsusf_weapons",
            "rhs_weapons",
            "ace_medical",
            "Taliban_fighters",
            "TIKA_BF2_Taliban",
            "TIKA_BF2_Armciv"
        };
        author = "Landric";
        authors[] = {"Landric"};
    };
};
